version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

  database:
    image: mysql
    restart: always
    ports:
      - "9812:3306"
    environment:
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=generic
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=tT7jN0oX0f111
volumes:
  app:
